user:
  outputs:
    dev:
      account: vnryrvy-tw19501
      auth_type: keypair
      client_session_keep_alive: false
      connect_retries: 3
      connect_timeout: 30
      database: SNAP_ANALYTICS
      private_key_passphrase: Love0705@
      private_key_path: /tmp/.dbt/keyfile.pem
      retry_on_database_errors: true
      role: null
      schema: DBT_SAKI
      threads: 2
      type: snowflake
      user: SAKISAKICHEN
      warehouse: COMPUTE_WH
  target: dev
